### ISSUE TITLE
Make migrations error

### ISSUE THREAD

**Issue by schollz** [sjsafranek/findauth#1]
```
-> % python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/makemigrations.py", line 63, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 312, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 282, in _reraise_missing_dependency
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 308, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration WallOfDenial.0001_initial dependencies reference nonexistent parent node ('auth', '0007_alter_validators_add_error_messages')
```

**Comment by schollz** [comment]
```
-> % python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 312, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 282, in _reraise_missing_dependency
    raise exc
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/loader.py", line 308, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/lib/python3.4/dist-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration WallOfDenial.0001_initial dependencies reference nonexistent parent node ('auth', '0007_alter_validators_add_error_messages')
```

**Comment by schollz** [comment]
Needs django > 1.85
